core/urls.py
from django.contrib import admin
from django.urls import path
from .views import Home, UserUpdateView, GeneralPage, chrome_download, firefox_download, userstastics, Delete_user, Usercreation

app_name = "core"

urlpatterns = [
    path('home/', Home.as_view(), name="home" ),
    path('userdetail/<slug:userid>/', userstastics.as_view(), name="userdetail" ),
    path('deleteuser/<slug:userid>/', Delete_user.as_view(), name="delete_user" ),
    path('update/<slug:userid>/', UserUpdateView.as_view(), name="update" ),
    path('create-user', Usercreation.as_view(), name="create_user" ),
    path('', GeneralPage.as_view(), name="index" ),
    path('chrome-download', chrome_download, name="chrome-download"),
    path('firefox-download', firefox_download, name="firefox-download"),
]

vpost/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls',namespace="core")),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT) 

templates/404error.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=0.3, shrink-to-fit=yes">
  <meta http-equiv="x-ua-compatible" content="ie=edge"> 
  <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/gif" sizes="16x16">
  <title>4o4</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <style>
  body{
  background-image: url("https://cdn.dribbble.com/users/285475/screenshots/2083086/dribbble_1.gif");
  background-color: #fff;
  color:#000;
  height: 100%;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  }
  @media only screen and (max-width: 1000px) {
  body {
    height: 100%;
    width: 320px;
  }
  h5,a{
  font-size: 3em;
  }
}
  </style>
</head>
<body>
    <center class="mt-5 pt-3">
    <h5 >Opps! Page not found</h5>
    <a class="btn rounded mt-2" style="background-color:#fff;color:#000;font-size: 3em" href="/">Go back to Homepage</a>
    </center>
    </div>
</body>
</html>

templates/413error.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>413</title>

<link href="https://fonts.googleapis.com/css?family=Montserrat:500" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Titillium+Web:700,900" rel="stylesheet">



<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<body>
<div id="notfound">
<div class="notfound">

<h1>Oops! This Page Could Not Be Found</h1>
<h2>Sorry, you are getting this error because your file(image) is too large.....</h2>
<p>Sorry but the page you are looking for does not exist, have been removed. name changed or is temporarily unavailable</p>
<a href="https://www.presimax.online/">Go To Homepage</a>
</div>
</div>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="de4b7f015ede2edfc39f0b2d-text/javascript"></script>
<script type="de4b7f015ede2edfc39f0b2d-text/javascript">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="de4b7f015ede2edfc39f0b2d-|49" defer=""></script></body>
</html>

templates/500error.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>500</title>

<link href="https://fonts.googleapis.com/css?family=Montserrat:500" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Titillium+Web:700,900" rel="stylesheet">



<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<body>
<div id="notfound">
<div class="notfound">
<h2>Oops! This Page Could Not Be Found</h2>
<p>Sorry but the page you are looking for does not exist, have been removed. name changed or is temporarily unavailable</p>
<a href="https://www.presimax.online/">Go To Homepage</a>
</div>
</div>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="de4b7f015ede2edfc39f0b2d-text/javascript"></script>
<script type="de4b7f015ede2edfc39f0b2d-text/javascript">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="de4b7f015ede2edfc39f0b2d-|49" defer=""></script></body>
</html>

templates/createuser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vpost | Create user</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap');
        html{
            height: 100%;    
        } 
        body{
            margin: 0;
            padding: 0;
            font-family: sans-serif;    
            background-color: #ffffff;
            background-image: linear-gradient(315deg, #ffffff 0%, #d7e1ec 74%);
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.3),
              0 0 25px rgba(0, 0, 0, 0.3), 0 0 50px rgba(0, 0, 0, 0.3), 0 0 100px rgba(0, 0, 0, 0.3);
        }
        .login-box{
            position: absolute;
            top: 50%;
            left: 50%;
            width: 400px;
            padding: 40px;
            transform: translate(-50%,-50%);
            background: #fff;
            box-sizing: border-box;
            border-radius: 10px;
        }
        .login-box h2{
            margin: 0 0 30px;
            padding: 0;
            color: #000;
            text-align: center;
        }
        .login-box .user-box{
            position: relative;
        }
        .login-box .user-box input {
            width: 100%;
            padding: 10px 0;
            font-size: 16px;
            color: #000;
            margin-bottom: 30px;
            border: none;
            border-bottom: 1px solid #000;
            outline: none;
            background: transparent;
          }
          .login-box .user-box label {
            position: absolute;
            top:0;
            left: 0;
            padding: 10px 0;
            font-size: 16px;
            color: #000;
            pointer-events: none;
            transition: .5s;
          }
          .login-box .user-box input:focus ~ label,
          .login-box .user-box input:valid ~ label{
              top: -20px;
              left: 0;
              color: #000;
              font-size: 12px;
          }
          .btn{
            position: relative;
            display: block;
            color: #fff;
            background-color: #4BBEFA;
            font-size: 1rem;
            text-decoration: none;
            overflow: hidden;
            transition: 0.5s;
            letter-spacing: 2px;
            width: 95%;
            height: auto;
            padding: 0.6rem 0.7rem;    
            border-radius: 6px;
            font-weight: 700;
            font-family: 'Poppins', sans-serif;
          }
        
          a{
            text-decoration: none;
            overflow: hidden;
            color: #000;
            letter-spacing: 1px;
          }
        
          .forgot-pass, .btn-cls{
            display: flex;
            flex-wrap: wrap;
            justify-content: end;
            align-items: center;
            cursor: pointer;
          }
        
          .btn{
            border: none;    
          }
        
          .btn-cls{
            justify-content: center;
            margin-top: 2.5rem;
          }
          
        </style>
</head>
<body>
    <form class="login login-box" method="POST" action="{% url 'core:create_user' %}">
        <h2>Create User</h2>
        {% csrf_token %}
        <div class="user-box">
            <input type="text" name="username" required>
        <label>Username</label>    
        </div>
        <div class="user-box">
            <input type="password" name="password" required>
            <label>Password</label>
        </div>            
        <div class="user-box">
            <input type="email" name="email" required>
            <label>Email</label>
        </div>                         
        
        <div class="btn-cls">
          <button class="btn" type="submit">Create User</button>
        </div>
      </form>    
</body>
</html>
  

templates/edituser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vpost | Update user</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap');
        html{
            height: 100%;    
        } 
        body{
            margin: 0;
            padding: 0;
            font-family: sans-serif;    
            background-color: #ffffff;
            background-image: linear-gradient(315deg, #ffffff 0%, #d7e1ec 74%);
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.3),
              0 0 25px rgba(0, 0, 0, 0.3), 0 0 50px rgba(0, 0, 0, 0.3), 0 0 100px rgba(0, 0, 0, 0.3);
        }
        .login-box{
            position: absolute;
            top: 50%;
            left: 50%;
            width: 400px;
            padding: 40px;
            transform: translate(-50%,-50%);
            background: #fff;
            box-sizing: border-box;
            border-radius: 10px;
        }
        .login-box h2{
            margin: 0 0 30px;
            padding: 0;
            color: #000;
            text-align: center;
        }
        .login-box .user-box{
            position: relative;
        }
        .login-box .user-box input {
            width: 100%;
            padding: 10px 0;
            font-size: 16px;
            color: #000;
            margin-bottom: 30px;
            border: none;
            border-bottom: 1px solid #000;
            outline: none;
            background: transparent;
          }
          .login-box .user-box label {
            position: absolute;
            top:0;
            left: 0;
            padding: 10px 0;
            font-size: 16px;
            color: #000;
            pointer-events: none;
            transition: .5s;
          }
          .login-box .user-box input:focus ~ label,
          .login-box .user-box input:valid ~ label{
              top: -20px;
              left: 0;
              color: #000;
              font-size: 12px;
          }
          .btn{
            position: relative;
            display: block;
            color: #fff;
            background-color: #4BBEFA;
            font-size: 1rem;
            text-decoration: none;
            overflow: hidden;
            transition: 0.5s;
            letter-spacing: 2px;
            width: 95%;
            height: auto;
            padding: 0.6rem 0.7rem;    
            border-radius: 6px;
            font-weight: 700;
            font-family: 'Poppins', sans-serif;
          }
        
          a{
            text-decoration: none;
            overflow: hidden;
            color: #000;
            letter-spacing: 1px;
          }
        
          .forgot-pass, .btn-cls{
            display: flex;
            flex-wrap: wrap;
            justify-content: end;
            align-items: center;
            cursor: pointer;
          }
        
          .btn{
            border: none;    
          }
        
          .btn-cls{
            justify-content: center;
            margin-top: 2.5rem;
          }
          
        </style>
</head>
<body>
    {% url 'core:update' user.userid as url %}
    <form class="login login-box" method="POST" action="{{ url }}">
        <h2>Edit User</h2>
        {% csrf_token %}    
        <div class="user-box">
            <input type="password" name="password" value="{{ user.send }}"  required>
            <label>Password</label>
        </div>
        
        <div class="">
            Disable : <input type="checkbox" name="status"> 
        </div>      
        
                                 
        
        <div class="btn-cls">
          <button class="btn" type="submit">Edit</button>
        </div>
      </form>    
</body>
</html>
  

templates/home.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">    
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VPost | Dashboard</title>            
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>    
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap');
        *{
            box-sizing: border-box;
            font-family: 'Poppins', sans-serif;
        }
        body{
            background-color: #F8F8FF;
            /* background-image: linear-gradient(315deg, #d9d9d9 0%, #f6f2f2 74%);             */
        }   
        a{
            color: inherit;
            text-decoration: none;
        }     
        .graphs{
            width: 100%;
            height: auto;
            display: flex;
            flex: auto;
            flex-direction: row;
            flex-wrap: wrap;            
            justify-content: space-around;
            align-items: center;
        }    
        .container{
            padding: 0.5rem;            
            margin: 0.5rem;
        }   
        .card-graph{
            background-color: #fff;
            border-radius: 12px;
            margin: 1rem;
            padding: 1rem 2rem;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.05),
            0 0 25px rgba(0, 0, 0, 0.05), 0 0 50px rgba(0, 0, 0, 0.05), 0 0 100px rgba(0, 0, 0, 0.05);
        }
        .side-panel{
            position: absolute;
            height: max-content;
            left: 0;
            top: 0;
            width: 17%;
            background-color: #000;
            color: #fff;
            padding-top: 3rem;
        }
        .containerx{            
            position: absolute;
            right: 0;
            top: 0;
            width: 83%;
        }
        .white-btn{
            background-color: white;
            color: #000;
            font-weight: 500;
            border-radius: 7px;
            border: none;
            padding: 0.8rem 1.2rem;
            margin-left: 2rem;
            margin-top: 3rem;
            font-size: 1.2rem;
        }
        .user-details{
            margin-top: 2rem;
            font-size: 1.4rem;
        }
        .user-details > span{
            background-color: #36454f;
            padding: 1rem;
            width: 100%;
            display: block;
            border-left: 3.5px solid #6488ea;            
        }
        .user-details > .users{
            padding-left: 3rem;
            padding-top: 1rem;
        }
        .user-details > .users  a{                        
            transition: background-color 1s;
            cursor: pointer;
            width: 100%;  
            display: block;        
            padding: 1rem;
        }        
        .user-details > .users  a:hover, .span-active{
            background-color: #36454f;              
        }
        .heading{            
            margin-left: 5rem;
        }
        .card{
            background-color: #fff;
            width: 70%;
            border-radius: 12px;
            margin: 1rem auto;
            margin-left: 10rem;
            margin-top: 2rem;
            padding: 1rem 0;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.05),
            0 0 25px rgba(0, 0, 0, 0.05), 0 0 50px rgba(0, 0, 0, 0.05), 0 0 100px rgba(0, 0, 0, 0.05);
        }
        .statastics{
            width: 100%;
            background-color: #fff;
            padding: 0.7rem 0.5rem;
        }
        h3.ul{
            margin-top: 5rem;
            margin-left: 5rem;
        }
        .fa2x{
            font-size: 1.28rem;            
        }

        table {        
        border-collapse: collapse;
        width: 100%;                  
        }

        th{
            border-bottom: 0.9px solid #000;            
        }

        td, th {        
        text-align: left;
        margin-right: 5rem;
        padding: 8px;
        }
    </style>
</head>
<body>

    <div class="container">

        <div class="side-panel">
            <a class="white-btn" href="{% url 'core:create_user' %}">+ Create User</a>
            <div class="user-details">
                <span>Users</span>                
                <div class="users"> 
                    {% for user in users %}                  
                    <a href="{% url 'core:userdetail' user.userid %}">{{ user.user.username }}</a>
                    {% endfor %}                  
                </div>
            </div>
        </div>

        <div class="containerx">

            <div class="statastics">
                <h3 class="heading">Statastics</h3>
            </div>

            <div class="graphs">
                <div class="data-usage card-graph" >
                    <canvas id="myChart" width="460" height="350"></canvas>
                </div>                
            </div> 

            <span style="display: none;" id="data_used">{{data_used}}</span>
            <div class="daily-usage">
                
                <div class="users-list">
                    <h3 class="ul">Data usage</h3>
                    <div class="card">
                        <div class="users-table">
    
                            <table>
                                <tr>
                                    <th> </th>
                                    <th> </th>
                                    <th>Date</th>
                                    <th>  </th>
                                    <th>  </th>
                                    <th>Data Consumed(in GB)</th>                                    
                                    <th> </th>
                                </tr>                                   
    
                            {% for i,j in zipped %}
                            <tr>          
                                <td></td>                  
                                <td></td>
                                <td>{{i}}</td>
                                <td></td>
                                <td></td>
                                <td>{{j}}</td>                                
                                <td></td>                                
                            </tr>   
                            {% endfor %}
    
                            </table>
                                
                        </div>
                    </div>
                </div>

            </div>

        </div>
        
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js" integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw==" crossorigin="anonymous"></script>
    <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var data_in_str = document.getElementById('data_used').innerHTML        
        var data_dicts = JSON.parse(data_in_str)        
        var lables = Object.keys(data_dicts)
        var data = []
        var i = 0;
        for(let i=0; i<= lables.length; i++){
            data.push(data_dicts[lables[i]]);
        }                     
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: lables,
                datasets: [{
                    label: 'Data Used',
                    data: data,
                    borderColor: "#3e95cd",
                    backgroundColor: "#a4ceeb",
                    borderWidth: 3
                }]
            },
            options: {               
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });        
    </script>   
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vpost</title>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>    
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap');
        *{
            box-sizing: border-box;
            font-family: 'Poppins', sans-serif;
        }
        body{
            background-color: #F8F8FF;
            /* background-image: linear-gradient(315deg, #d9d9d9 0%, #f6f2f2 74%);             */
        }   
        a{
            color: inherit;
            text-decoration: none;
        }     
        .graphs{
            width: 100%;
            height: auto;
            display: flex;
            flex: auto;
            flex-direction: row;
            flex-wrap: wrap;            
            justify-content: space-around;
            align-items: center;
        }    
        .container{
            padding: 0.5rem;            
            margin: 0.5rem;
        }   
        .card-graph{
            background-color: #fff;
            border-radius: 12px;
            margin: 1rem;
            padding: 1rem 2rem;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.05),
            0 0 25px rgba(0, 0, 0, 0.05), 0 0 50px rgba(0, 0, 0, 0.05), 0 0 100px rgba(0, 0, 0, 0.05);
        }
        .side-panel{
            position: absolute;
            height: auto;
            left: 0;
            top: 0;
            width: 17%;
            background-color: #000;
            color: #fff;
            padding-top: 3rem;
        }
        .containerx{
            position: absolute;
            right: 0;
            top: 0;
            width: 83%;
        }
        .white-btn{
            background-color: white;
            color: #000;
            font-weight: 500;
            border-radius: 7px;
            border: none;
            padding: 0.8rem 1.2rem;
            margin-left: 2rem;
            margin-top: 3rem;
            font-size: 1.2rem;
        }
        .user-details{
            margin-top: 2rem;
            font-size: 1.4rem;
        }
        .user-details > span{
            background-color: #36454f;
            padding: 1rem;
            width: 100%;
            display: block;
            border-left: 3.5px solid #6488ea;            
        }
        .user-details > .users{
            padding-left: 3rem;
            padding-top: 1rem;
        }
        .user-details > .users  a{                        
            transition: background-color 1s;
            cursor: pointer;
            width: 100%;  
            display: block;        
            padding: 1rem;
        }
        .user-details > .users  a:hover, .span-active{
            background-color: #36454f;              
        }
        .card{
            background-color: #fff;
            border-radius: 12px;
            margin: 1rem auto;
            width: 90%;
            padding: 1rem 0;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.05),
            0 0 25px rgba(0, 0, 0, 0.05), 0 0 50px rgba(0, 0, 0, 0.05), 0 0 100px rgba(0, 0, 0, 0.05);
        }
        .row{
            display: flex;
            flex-direction: row;
            padding: 0.7rem 0;
        }
        .row > span{
            margin-right: 5rem;
        }
        .extra-space{
            margin-right: 12rem !important;
        }
        .row.head{
            padding: 0.7rem 0;
            margin: 0.1rem 0;
            border-bottom: 0.9px solid #000;
            font-weight: 600;
        }
        h3.ul{
            margin-top: 5rem;
            margin-left: 5rem;
        }
        .fa2x{
            font-size: 1.28rem;            
        }

        table {        
          border-collapse: collapse;
          width: 100%;
        }

        th{
            border-bottom: 0.9px solid #000;            
        }

        td, th {        
        text-align: left;
        padding: 8px;
        }
    </style>
</head>
<body>
    <div class="container">

        <div class="side-panel">
            <a class="white-btn" href="{% url 'core:create_user' %}">+ Create User</a>
            <div class="user-details">
                <span>Users</span>                
                <div class="users"> 
                    {% for user in users %}                  
                    <a href="{% url 'core:userdetail' user.userid %}">{{ user.user.username }}</a>
                    {% endfor %}                  
                </div>
            </div>
        </div>

        <div class="containerx">

            <div class="users-list">
                <h3 class="ul">Users Details</h3>
                <div class="card">
                    <div class="users-table">


                        <table>
                            <tr>
                                <th></th>
                                <th>User Id</th>
                                <th>Username</th>
                                <th>Traffic (total in GB)</th>
                                <th>Status</th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>                        

                        {% for user in users %}
                        <tr>          
                            <td></td>                  
                            <td>{{user.userid}}</td>
                            <td>{{user.user.username}}</td>
                            <td class="extra-space">{{user.data_used}}</td>
                            <td >{{user.status}}</td>
                            {% url 'core:update' user.userid as urly %}
                            <td class="fal fa-edit fa2x" onclick='location.href="{{ urly }}";' style="cursor: pointer;"></td>
                            <td></td>
                            {% url 'core:delete_user' user.userid as urlx %}
                            <td class="far fa-trash-alt fa2x" onclick='location.href="{{ urlx }}";' style="cursor: pointer;color: tomato;" ></td>
                        </tr>   
                        {% endfor %}

                        </table>

                    </div>
                </div>
            </div>

        </div>
        
    </div> 
    
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    
</body>
</html>

templates/index.html
{% load  static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VPost</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap');
        *{
            box-sizing: border-box;
            font-family: 'Poppins', sans-serif;
        }
        html{
            height: 100%;    
        } 
        body{
            margin: 0;
            padding: 0;
            font-family: sans-serif;    
            background-color: #ffffff;
            background-image: linear-gradient(315deg, #ffffff 0%, #d7e1ec 74%);            
        }
        .container{
            position: absolute;
            top: 50%;
            left: 50%;
            height: auto;
            width: auto;
            padding: 40px;
            transform: translate(-50%,-50%);
            background: #fff;
            box-sizing: border-box;
            border-radius: 10px;
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.05),
            0 0 25px rgba(0, 0, 0, 0.05), 0 0 50px rgba(0, 0, 0, 0.05), 0 0 100px rgba(0, 0, 0, 0.05);
        }
        .card{
            display: flex;      
            width: 20rem;      
            flex-direction: column;
            justify-content: center;
            align-items: center;
            margin: 3rem;            
        }
        .card img{
            width: 5rem;
            height: 5rem;
            object-fit: contain;
        }     
        .card p{
            justify-self: center;
            margin: 0 auto;
            width: auto;
        }   
        a{
            color: inherit;
            text-decoration: none;
            font-size: 1.4rem;
            font-weight: 600;
            align-self: center;
            margin: 1rem auto;   
        }        
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="image">
                <img src="{% static '/images/chrome.png' %}" alt="chrome Download">
            </div>
            <p>This extension is for chrome. After installation set options to forced proxy and allow private browsing.</p>
            <a href="{% url 'core:chrome-download' %}">Download</a>
        </div>
        <div class="card">
            <div class="image">
                <img src="{% static '/images/firefox.png' %}" alt="firefox Download">
            </div>
            <p>This extension is for Firefox. To install go to <em>about:debugging</em> page and load temporary extension. After installation allow private browsing.</p>
            <a href="{% url 'core:firefox-download' %}">Download</a>
        </div>
    </div>
</body>
</html>